local print
local warn
local error
local setfenv
local gcinfo
local getmodules
local rawlen
local Delay
local xpcall
local ypcall
local delay
local loadstring
local printidentity
local require
local setmetatable
local next
local time
local rawequal
local collectgarbage
local rawset
local tostring
local unpack
local rawget
local getmetatable
local Print
local Warn
local Error
local listfiles
local getnamecallmethod
local replacecclosure
local firetouchinterest
local getsenv
local writecustomasset
local clearteleportqueue
local base64_decode
local getreg
local is_synapse_function
local rconsoleinput
local getfpsmax
local rconsoleprint
local sethiddenproperty
local setcontext
local makewriteable
local setstack
local get_nil_instances
local deletefolder
local gettenv
local getcurrentline
local getnilinstances
local getcontext
local getgc
local get_thread_context
local getscripts
local consoleclear
local restoreclosure
local appendfile
local zstddcompress
local setthreadcontext
local rconsolecreate
local get_script_function
local getcallingscript
local queueonteleport
local consolecreate
local logprint
local isfile
local getscriptfunction
local getcaller
local base64encode
local getrenv
local get_loaded_modules
local warnuiconsole
local securecall
local consoleinput
local setfflag
local protectfunction
local get_instances
local getrawmetatable
local get_calling_script
local gethwid
local hookmetamethod
local logerror
local hookfunc
local getcustomasset
local replaceclosure
local get_namecall_method
local getscriptenvs
local getthreadidentity
local setrawmetatable
local get_namecall_method
local clonefunction
local isrenderobj
local loginfo
local compareinstances
local rconsolename
local delfile
local getstack
local readfile
local rconsolewarn
local gethui
local getsynasset
local readfile
local getspecialinfo
local setnamecallmethod
local getconnections
local checkcaller
local setreadonly
local GrantAccess
local restorefunc
local checkclosure
local dumpstring
local iswriteable
local getupvalues
local rconsoleclear
local consoleerr
local replacefunc
local set_thread_identity
local getinfo
local consolewarn
local clonefunc
local loadfile
local logwarn
local hookfunction
local setrbxclipboard
local runcode
local consolesettitle
local consoledestroy
local getfflag
local setthreadcontext
local rconsoleerror
local runautoexec
local getthreadcontext
local isfunctionhooked
local replacefunction
local cloneref
local getprotos
local getscriptbytecode
local detour_function
local get_gc_objects
local getmenv
local rconsoleshow
local iswindowactive
local firesignal
local makefolder
local isscriptable
local detourfunction
local makewriteable
local getscripthash
local require
local getObjects
local getallthreads
local getbatterypercentage
local getstateenv
local StartUp
local lz4compress
local getrenderproperty
local consoleprint
local get_modules
local printuierror
local printdebug
local cleardrawcache
local validlevel
local printuiconsole
local zstdcompress
local delfolder
local getgenv
local set_namecall_method
local readuifile
local infouiconsole
local getscriptfromthread
local consoleerror
local setrenderproperty
local emulate_call
local setconstant
local getconstants
local getinstances
local getloadedmodules
local erroruiconsole
local isvalidlevel
local iscclosure
local restorefunction
local get_scripts
local setclipboard
local isreadonly
local base64_encode
local writefile
local getconstant
local iswriteable
local getscriptclosure
local printuiwarn
local setthreadidentity
local getproto
local deletefile
local writeuifile
local base64decode
local ishooked
local gethiddenproperty
local rconsoleerr
local getallthreads
local newcclosure
local setscriptable
